### ISSUE TITLE
"code coming soon"

### ISSUE THREAD

**Issue by chrisbward** [jshilong/flashface-page#1]
Like the other dozen Alibaba projects?!?

Don't think so.

**Comment by jshilong** [comment]
> Like the other dozen Alibaba projects?!?
> 
> Don't think so.

After a period of review, the code is finally open source. You are welcome to try it.
https://github.com/ali-vilab/FlashFace

I have been involved in a total of 9 research projects up to this point. Each of these projects has been open source, and I have dedicated a great deal of effort to them.  If there are no force majeure events, I will open-source every project I work on.
